language: python
notifications:
  email: false
matrix:
  include:
    - name: "Python 3.7.x on Xenial Linux"
      python: 3.7
      dist: xenial
      install:
        - pip3 install --upgrade pip
        - pip3 install flake8 pydocstyle black
        - pip3 install pytest-cov codecov coverage
    - name: "Python nightly on Xenial Linux"
      python: "nightly"
      dist: xenial
      install:
        - pip3 install --upgrade pip
        - pip3 install flake8 pydocstyle black
        - pip3 install pytest-cov codecov coverage
script:
  - pytest --cov=./
  - coverage run verse.py
  - flake8
  - pydocstyle scripture.py
  - black --check .
  - codecov
