language: python
notifications:
  email: false
matrix:
  include:
    - name: "Python 3.7.x on Xenial Linux"
      python: 3.7
      dist: xenial
      install:
        - pip3 install --upgrade pip
        - pip3 install flake8 pydocstyle
    - name: "Python nightly on Xenial Linux"
      python: "nightly"
      dist: xenial
      install:
        - pip3 install --upgrade pip
        - pip3 install flake8 pydocstyle
script:
  - pytest
  - flake8 scripture.py verse.py test_scripture.py
  - pydocstyle scripture.py
