#!/bin/bash
pytest test_random_verse.py --cov=./
PYTEST_EXIT_STATUS=$?
coverage run random_verse.py
TEST_EXIT_STATUS=$?
python3 --version
if ! [ $? -eq 127 ]
then
  python3 -m flake8 random_verse.py test_random_verse.py
else
  flake8 random_verse.py test_random_verse.py
fi
FLAKE8_EXIT_STATUS=$?
pydocstyle random_verse.py
PYDOC_EXIT_STATUS=$?
black --check .
BLACK_EXIT_STATUS=$?
echo "======Summary====="
if [ $PYTEST_EXIT_STATUS -eq 0 ] && [ $TEST_EXIT_STATUS -eq 0 ]
then
  tput setaf 2
  echo "Tests passed"
else
  tput setaf 1
  echo "Tests failed"
fi
if [ $FLAKE8_EXIT_STATUS -eq 0 ]
then
  tput setaf 2
  echo "Flake8 likes it"
else
  tput setaf 1
  echo "Flake8 complains"
fi
if [ $PYDOC_EXIT_STATUS -eq 0 ]
then
  tput setaf 2
  echo "PEP 257 likes it"
else
  tput setaf 1
  echo "PEP 257 complains"
fi
if [ $BLACK_EXIT_STATUS -eq 0 ]
then
  tput setaf 2
  echo "Black likes it"
else
  tput setaf 1
  echo "Black complains"
fi
tput setaf 9
